In [84]:
import pandas as pd
import numpy as np
import xlrd

In [85]:
df = pd.read_csv('20scores.txt',sep='\t',header=None)

In [1]:
sheet= data.sheet_by_name('Sheet4')
nrows = sheet.nrows  
ncols = sheet.ncols  

NameError: name 'data' is not defined

In [5]:
[nrows,ncols]

[188581, 13]

In [6]:
df = pd.DataFrame(np.zeros((nrows,ncols)))
for i in range(ncols):
    df.loc[:,i] = pd.DataFrame(sheet.col_values(i))

In [86]:
df.columns = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','AA','AB','AC','AD','AE','AF','AG','AH']
S=df.copy()
S

A  B  C  D  E  F  G  H  I  J ...  Y  Z  AA  AB  AC  AD  AE  AF  AG  AH
0      0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
1      1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
2      0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
3      1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
4      0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
5      1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
6      1  1  1  1  1  0  0  0  1  0 ...  1  0   1   0   1   1   0   0   0   0
7      0  0  0  0  0  0  0  0  0  1 ...  0  1   0   0   0   0   0   1   1   1
8      1  1  1  1  1  1  1  1  1  0 ...  0  1   0   1   0   1   0   1   1   0
9      1  1  1  1  1  1  1  1  1  0 ...  1  0   1   1   1   0   0   0   0   0
10     0  0  0  0  0  1  1  1  0  1 ...  1  0   1   1   1   1   1   0   0   1
11     0  0  0  0  0  0  0  0  0  1 ...  0  1   0   0   0   0   0   1   1   1
12     0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
13     0  0  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
14     1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
15     1  1  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
16     1  1  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
17     0  0  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
18     1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
19     1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
20     0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
21     0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
22     0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
23     1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
24     0  0  1  0  0  0  0  0  0  0 ...  1  0   0   0   1   0   0   0   0   0
25     1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
26     0  0  0  1  1  1  1  1  1  0 ...  0  0   0   0   0   1   0   0   0   0
27     0  0  0  0  0  0  0  0  0  0 ...  1  0   0   1   0   0   0   1   1   0
28     1  1  0  1  1  1  1  1  1  1 ...  0  1   1   1   1   1   0   0   0   0
29     1  1  1  0  0  0  0  0  0  1 ...  0  1   1   0   0   0   0   1   1   0
...   .. .. .. .. .. .. .. .. .. .. ... .. ..  ..  ..  ..  ..  ..  ..  ..  ..
94260  0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
94261  0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
94262  1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
94263  1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
94264  0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
94265  1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   0   1   1   0
94266  1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
94267  1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
94268  1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
94269  0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
94270  0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
94271  0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
94272  1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
94273  1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
94274  0  0  1  0  0  1  1  1  0  1 ...  1  1   1   1   1   1   1   1   1   1
94275  0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
94276  0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
94277  1  1  0  1  1  0  0  0  1  0 ...  0  0   0   0   0   0   0   0   0   0
94278  1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
94279  1  1  1  1  1  1  1  1

In [88]:
S1 = pd.DataFrame(S)
S1.to_csv("com_rating_2.csv",index=None, header= True)

In [89]:
S = pd.read_csv("com_rating_2.csv",index_col=False,)
S.head(-1)

A  B  C  D  E  F  G  H  I  J ...  Y  Z  AA  AB  AC  AD  AE  AF  AG  AH
0      0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
1      1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
2      0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
3      1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
4      0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
5      1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
6      1  1  1  1  1  0  0  0  1  0 ...  1  0   1   0   1   1   0   0   0   0
7      0  0  0  0  0  0  0  0  0  1 ...  0  1   0   0   0   0   0   1   1   1
8      1  1  1  1  1  1  1  1  1  0 ...  0  1   0   1   0   1   0   1   1   0
9      1  1  1  1  1  1  1  1  1  0 ...  1  0   1   1   1   0   0   0   0   0
10     0  0  0  0  0  1  1  1  0  1 ...  1  0   1   1   1   1   1   0   0   1
11     0  0  0  0  0  0  0  0  0  1 ...  0  1   0   0   0   0   0   1   1   1
12     0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
13     0  0  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
14     1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
15     1  1  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
16     1  1  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
17     0  0  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
18     1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
19     1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
20     0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
21     0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
22     0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
23     1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
24     0  0  1  0  0  0  0  0  0  0 ...  1  0   0   0   1   0   0   0   0   0
25     1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
26     0  0  0  1  1  1  1  1  1  0 ...  0  0   0   0   0   1   0   0   0   0
27     0  0  0  0  0  0  0  0  0  0 ...  1  0   0   1   0   0   0   1   1   0
28     1  1  0  1  1  1  1  1  1  1 ...  0  1   1   1   1   1   0   0   0   0
29     1  1  1  0  0  0  0  0  0  1 ...  0  1   1   0   0   0   0   1   1   0
...   .. .. .. .. .. .. .. .. .. .. ... .. ..  ..  ..  ..  ..  ..  ..  ..  ..
94259  0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
94260  0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
94261  0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
94262  1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
94263  1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
94264  0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
94265  1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   0   1   1   0
94266  1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
94267  1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
94268  1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
94269  0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
94270  0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
94271  0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
94272  1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
94273  1  1  1  1  1  1  1  1  1  1 ...  1  1   1   1   1   1   1   1   1   1
94274  0  0  1  0  0  1  1  1  0  1 ...  1  1   1   1   1   1   1   1   1   1
94275  0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
94276  0  0  0  0  0  0  0  0  0  0 ...  0  0   0   0   0   0   0   0   0   0
94277  1  1  0  1  1  0  0  0  1  0 ...  0  0   0   0   0   0   0   0   0   0
94278  1  1  1  1  1  1  1  1

In [90]:
[S_rows, S_cols] = S.shape
S.shape

(94290, 34)

In [91]:
S = np.mat(S)
S

matrix([[0, 0, 0, ..., 0, 0, 0],
        [1, 1, 1, ..., 1, 1, 1],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [92]:
S_new = S.T * S
S_new

matrix([[47145, 46191, 36113, ..., 35548, 35555, 29139],
        [46191, 47145, 36499, ..., 35661, 35668, 29223],
        [36113, 36499, 47145, ..., 38454, 38452, 32707],
        ...,
        [35548, 35661, 38454, ..., 47145, 46959, 37978],
        [35555, 35668, 38452, ..., 46959, 47145, 37976],
        [29139, 29223, 32707, ..., 37978, 37976, 38954]], dtype=int64)

In [93]:
S_I = S_new.I
S_I.shape

(34, 34)

In [94]:
X = 2*S-1
X

matrix([[-1, -1, -1, ..., -1, -1, -1],
        [ 1,  1,  1, ...,  1,  1,  1],
        [-1, -1, -1, ..., -1, -1, -1],
        ...,
        [ 1,  1,  1, ...,  1,  1,  1],
        [-1, -1, -1, ..., -1, -1, -1],
        [-1, -1, -1, ..., -1, -1, -1]], dtype=int64)

In [95]:
X_new = X.T * X
X_new

matrix([[94290, 90474, 50162, ..., 47902, 47930, 38648],
        [90474, 94290, 51706, ..., 48354, 48382, 38984],
        [50162, 51706, 94290, ..., 59526, 59518, 52920],
        ...,
        [47902, 48354, 59526, ..., 94290, 93546, 74004],
        [47930, 48382, 59518, ..., 93546, 94290, 73996],
        [38648, 38984, 52920, ..., 74004, 73996, 94290]], dtype=int64)

In [96]:
X_I = X_new.I
X_I.shape

(34, 34)

In [97]:
# a1=np.mat([1,1]).T
# a2=np.mat([2,2])
# a3=np.dot(a2,a1)
# a3
a = np.ones((S_cols,1))
r = np.ones((S_cols,1))
r.shape


(34, 1)

In [99]:
# r[0]=0.5287
r[0]=0.7025
r[1]=0.7053  # 6
r[2]=0.7777
r[3]=0.7831
r[4]=0.7833
r[5]=0.7835
r[6]=0.7837  #11
r[7]=0.7841
r[8]=0.7896
# r[11]=0.8502  # 14
r[9]=0.8496  # 15
r[10]=0.8498
r[11]=0.8084
r[12]=0.8484
r[13]=0.8495
r[14]=0.8517

# # new n1-nx..
r[15]=0.8589
r[16]=0.8609
r[17]=0.8611
r[18]=0.8618
r[19]=0.8684
r[20]=0.8292
# #new try
r[21]=0.8621  # norm data X with weights
r[22]=0.8622  # norm data X no weights
r[23]=0.8623  # combine score no weights
r[24]=0.8627  # combine score with weights
r[25]=0.8670
# r[26]=0.8589
r[26]=0.8617
r[27]=0.8619
r[28]=0.8620
r[29]=0.8623
r[30]=0.8660
r[31]=0.8662
r[32]=0.8663
r[33]=0.8706




In [100]:
X_t_Y = S_rows*2*r - S_rows
a = np.dot(X_I,X_t_Y)
print(a)
a.shape

[[-0.018726  ]
 [-0.00785245]
 [ 0.03885758]
 [-0.02422435]
 [ 0.06424675]
 [-0.01652212]
 [ 0.00813225]
 [-0.01504474]
 [ 0.00567875]
 [-0.28315777]
 [ 0.51476208]
 [ 0.05329322]
 [-0.11183498]
 [ 0.01271381]
 [ 0.08453474]
 [ 0.04606354]
 [ 0.13334849]
 [-0.07865169]
 [ 0.05106127]
 [ 0.20786679]
 [-0.00445076]
 [ 0.04590087]
 [ 0.05417225]
 [ 0.05992348]
 [ 0.0585093 ]
 [-0.01013543]
 [ 0.04170009]
 [ 0.02482965]
 [ 0.03056848]
 [ 0.02976458]
 [-0.20412036]
 [-0.0463969 ]
 [-0.03333211]
 [ 0.19671186]]


(34, 1)

In [101]:
y = X*a
y = pd.DataFrame(y)
y.columns = ['rating']
y.head(12)

rating
0  -0.908190
1   0.908190
2  -0.908190
3   0.908190
4  -0.908190
5   0.908190
6   0.092321
7  -0.022697
8  -0.474369
9   0.263064
10  0.980860
11 -0.013795

In [102]:
sorted_scores = y.iloc[6:12,0].sort_values()
sorted_scores.index
y.iloc[sorted_scores.index[0:3],0] = 11
y.head(12)

rating
0   -0.908190
1    0.908190
2   -0.908190
3    0.908190
4   -0.908190
5    0.908190
6    0.092321
7   11.000000
8   11.000000
9    0.263064
10   0.980860
11  11.000000

In [103]:
Y = y.copy()
Y

rating
0      -0.908190
1       0.908190
2      -0.908190
3       0.908190
4      -0.908190
5       0.908190
6       0.092321
7      11.000000
8      11.000000
9       0.263064
10      0.980860
11     11.000000
12     -0.917092
13      0.961347
14      0.908190
15     -0.961347
16     -0.961347
17      0.961347
18      0.917092
19      0.908190
20     -0.908190
21     -0.908190
22     -0.908190
23      0.908190
24     -0.450754
25      0.908190
26     -0.419078
27     -0.474065
28     -0.123977
29     -0.251051
...          ...
94260  -0.908190
94261  -0.816063
94262   0.908190
94263   0.908190
94264  -0.908190
94265   0.424048
94266   0.908190
94267   0.908190
94268   0.908190
94269  -0.908190
94270  -0.908190
94271  -0.908190
94272   0.908190
94273   0.908190
94274   0.869945
94275  -0.908190
94276  -0.908190
94277  -0.869945
94278   0.908190
94279   0.908190
94280  -0.908190
94281   0.908190
94282  -0.908190
94283  -0.908190
94284   0.908190
94285   0.828145
94286  -0.908190
94287   0.908190
94288  -0.908190
94289  -0.828145

[94290 rows x 1 columns]

In [104]:
def getRating(total_score_M):
    for i in range(15715):
        sorted_scores = total_score_M.iloc[6*i:6*(i+1),0].sort_values()
        
        for j in range(6):
            if j <3:
                total_score_M.iloc[sorted_scores.index[j],0] = 0
            else:
                try:  
                    total_score_M.iloc[sorted_scores.index[j],0] = 1
                except IndexError:
                    continue
    
    return total_score_M

In [105]:
import time as tm
start_time = tm.time()
combined_rating = getRating(Y)
print("Finished, use %.2f s" %(tm.time()-start_time))

Finished, use 17.53 s


In [106]:
# is_05 = combined_rating['rating']==1
# combined_rating[is_05].count()
combined_rating.head(11)

rating
0      0.0
1      1.0
2      0.0
3      1.0
4      0.0
5      1.0
6      0.0
7      1.0
8      1.0
9      0.0
10     0.0

In [107]:
rating_1 = combined_rating.astype(int)
rating_1.to_csv('c8_X.txt',index=None, header= False)

In [108]:
combined_rating.to_csv('combined_rating.txt',header=False, index=False, sep='\t', mode='a')